load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "bazel_skylib",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.2.0/bazel-skylib-1.2.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.2.0/bazel-skylib-1.2.0.tar.gz",
    ],
    sha256 = "af87959afe497dc8dfd4c6cb66e1279cb98ccc84284619ebfec27d9c09a903de",
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

# Rust

http_archive(
    name = "rules_rust",
    sha256 = "f670898f3ba391ec3cc2b18aef37a92a4f602fa68c9e6cb52d201d0966af369b",
    strip_prefix = "rules_rust-e7a9b8b1843ffb0e1c6c645590b0ac18b28f11ae",
    urls = [
        # Master branch as of 2022-02-15
        "https://github.com/bazelbuild/rules_rust/archive/e7a9b8b1843ffb0e1c6c645590b0ac18b28f11ae.tar.gz",
    ],
)
load("@rules_rust//rust:repositories.bzl", "rust_register_toolchains", "rust_repository_set")
RUST_VERSION = "1.56.1"
rust_register_toolchains(version = RUST_VERSION, edition="2018", rustfmt_version = RUST_VERSION)
rust_repository_set(
    name = "rust_apple_x86_64",
    edition = "2018",
    version = RUST_VERSION,
    rustfmt_version = RUST_VERSION,
    exec_triple = "x86_64-apple-darwin",
    extra_target_triples=["aarch64-linux-android", "i686-linux-android", "x86_64-linux-android"]
)

load("//third_party/cargo:crates.bzl", "raze_fetch_remote_crates")
raze_fetch_remote_crates()

# Android

RULES_ANDROID_VERSION = "e8fbc49f913101e846235b9c9a31b3aa9788364a"
RULES_ANDROID_SHA256 = "6a3cfb7b7e54cf704bf2ff169bde03666ae3b49a536c27a5f43d013388a7c38d"
http_archive(
    name = "rules_android",
    strip_prefix = "rules_android-%s" % RULES_ANDROID_VERSION,
    url = "https://github.com/bazelbuild/rules_android/archive/%s.tar.gz" % RULES_ANDROID_VERSION,
    sha256 = RULES_ANDROID_SHA256
)

# Newer build tools don't work
android_sdk_repository(name = "androidsdk", build_tools_version = "30.0.3")
android_ndk_repository(name = "androidndk")

# Java dependencies

RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        # Newer versions don't work yet, probably has to do with build tools 30.0.0 above^
        "androidx.appcompat:appcompat:1.3.1",
        "androidx.constraintlayout:constraintlayout:2.0.4",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://maven.google.com",
    ],
)
